#not used currently , config is in move_base.yaml , using dwa planner 
controller_frequency: 5.0

TrajectroyPlannerROS: #namespace for base_local_planner
  
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 0.20
  min_in_place_vel_theta: 0.0

  acc_lim_theta: 0
  acc_lim_x: 0.05
  acc_lim_y: 0

  holonomic_robot: false

  sim_time: 1
  sim_granularity: 0.1
  vtheta_samples: 10
  gdist_scale: 5
  goal_distance_bias: 5
  heading_scoring: true
  heading_scoring_timestep: 0.1
  oscillation_reset_dist: 0.7
  dwa: false  #TODO , try true 

  
