global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 4.0
  static_map: true
  track_unknown_space: true

  obstacle_range: 2.0
  raytrace_range: 1.0
  inflation_radius: 0.1 #0.2 #0.4 #was 0.1 #was 0.4 
  resolution: 0.05
  
