local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 4.0

  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  track_unknown_space: true
  #combination_method 0
  obstacle_range: 2.0
  raytrace_range: 2.0 #was 1.0
  inflation_radius: 0.1 #0.1 #was 0.4 was 0.05 #was 0.1# was 0.2 , in real robot Im trying 0.1





