type: "diff_drive_controller/DiffDriveController"
publish_rate: 50

left_wheel: "base_to_left_wheel"
right_wheel: "base_to_right_wheel"

wheel_separation: 0.27

# Odometry covariances for the encoder output of the robot. These values should
# be tuned to your robot's sample odometry data, but these values are a good place
# to start
pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

# Top level frame (link) of the robot description
base_frame_id: base_link
enable_odom_tf: false
# Velocity and acceleration limits for the robot
linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 20  # m/s
    has_acceleration_limits: true
    max_acceleration       : 5   # m/s^2
angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 5  # rad/s
    has_acceleration_limits: true
    max_acceleration       : 2   # rad/s^2
